#!/bin/bash

echo "Starting deployment to Netlify..."
echo "Site: ccqsrnavigator"
echo "Directory: dist"
echo ""
echo "To deploy manually:"
echo "1. Go to: https://app.netlify.com/projects/ccqsrnavigator"
echo "2. Click on 'Deploys' tab"
echo "3. Look for 'Deploy settings' -> 'Build & deploy'"
echo "4. Trigger a new deploy from there"
echo ""
echo "OR use GitHub:"
echo "1. Push this code to a GitHub repo"
echo "2. In Netlify, go to Site settings -> Build & deploy -> Continuous deployment"
echo "3. Link your GitHub repo"
echo ""
echo "The environment variables are already configured in Netlify."
echo "Database URL and Basecamp tokens are set."